launch=bind
bind-config=/home/isucon/dns/named.conf
bind-check-interval=0
api=yes
api-key=isudns
webserver=yes
local-port=53
security-poll-suffix=
setgid=pdns
setuid=pdns
cache-ttl=0
negquery-cache-ttl=0
query-cache-ttl=0
zone-cache-refresh-interval=10
zone-metadata-cache-ttl=60
log-dns-queries=no
log-dns-details=no
loglevel=4
